FROM public.ecr.aws/lambda/python:3.12

# Copy only requirements first
COPY requirements.txt .

# Install dependencies (no build tools needed for pinned versions)
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the function code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "main.handler" ]
