service: taxi-demand-backend
useDotenv: true

provider:
  name: aws
  region: us-east-1 # Change to your preferred region
  stage: prod
  memorySize: 2048
  timeout: 30
  ecr:
    images:
      appimage:
        path: ../
        file: backend/Dockerfile.lambda

functions:
  api:
    image:
      name: appimage
    events:
      - httpApi: '*'
    environment:
      DATABASE_URL: "postgresql://postgres:Sachin2442006@database-1.cdoqem628xxj.eu-north-1.rds.amazonaws.com:5432/postgres"
      SMTP_EMAIL: "demandsightsupport@gmail.com"
      SMTP_APP_PASSWORD: "xtjjmdkingebuvqw"
