import { motion } from 'framer-motion';
import { Shield, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Privacy() {
  return (
    <div className="min-h-screen bg-[#050505] text-white font-sans p-8 md:p-24 selection:bg-orange-500/30">
      <div className="max-w-3xl mx-auto">
        <Link to="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-orange-500 transition-colors mb-12 uppercase text-xs font-bold tracking-widest">
          <ArrowLeft size={16} />
          Back to Home
        </Link>
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 rounded-2xl bg-orange-500/10 flex items-center justify-center text-orange-500">
              <Shield size={24} />
            </div>
            <h1 className="text-4xl font-black italic tracking-tight uppercase">Privacy Policy</h1>
          </div>

          <div className="space-y-8 text-slate-400 leading-relaxed font-medium">
            <section>
              <h2 className="text-white text-xl font-bold mb-4">1. Data Collection</h2>
              <p>DemandSight collects geospatial mobility data and user account information to provide accurate demand forecasts. This data is encrypted and handled with enterprise-grade security protocols.</p>
            </section>

            <section>
              <h2 className="text-white text-xl font-bold mb-4">2. Usage Rights</h2>
              <p>Forecasts generated by DemandSight are for the exclusive use of the registered account holder (Fleet Operator or Solo Driver). Redistribution of raw forecast data is prohibited.</p>
            </section>

            <section>
              <h2 className="text-white text-xl font-bold mb-4">3. Security</h2>
              <p>We use industry-standard JWT authentication and role-based access control to ensure that only authorized users can access sensitive operational maps and data.</p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
